# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${project.name}
# !-----------------------------------------------------------------------------------------------!
#
#    For support and documentation, please visit:
#    - https://github.com/markings31/${project.name}/wiki
#
# !-----------------------------------------------------------------------------------------------!
#    1) COLOR CODES are supported with the '&' character.
#       - For usage, see http://minecraftwiki.net/wiki/Formatting_codes
#       - When you use them, place quotes around the message like this: "Hello &cworld."
#       - To use HEX colors, use #123456 syntax: "Hello #123456world."
#
#    2) TO HIDE any message, set it to 'none'.
#
#    3) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding. See
#       - https://github.com/markings31/${project.name}/wiki/Use-Right-Encoding
#
#    4) JSON is supported.
#       - For usage, see https://github.com/markings31/${project.name}/wiki/JSON
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Notifications Section
# -------------------------------------------------------------------------------------------------
Notifications:

  # Broadcast Messages
  Broadcast:

    # Enable broadcast messages?
    Enable: true

    # Should all broadcast messages be forwarded to connected Bungeecord servers?
    # NOTE: This requires the "BubbleBungee" addon (included with the download) to
    # be installed onto your Bungeecord proxy server.
    Bungeecord: false

    # The delay between each broadcast message.
    Delay: 90 seconds

    # Should the broadcast messages be outputted randomly?
    # Setting this to false will broadcast them in order.
    Random_Message: false

    # Should all broadcast messages be centered automatically?
    Center_All: false

    # Which worlds should the broadcast messages be sent to?
    Worlds:
      - 'world'

    # What sound should be played when a message is broadcast?
    # A list of the compatible values can be found here:
    # https://gist.github.com/NiklasEi/7bd0ffd136f8459df0940e4501d47a8a
    Sound: NOTE_PLING, 1F, 1.5F

    Header: "&8<smooth_line>"
    Footer: "&8<smooth_line>"

    # The messages that will be broadcasted to players.
    Messages:
      Example_Message:
        Permission: bubble.vip
        Message:
          - '&6This is an example message!'
      Multi_Line_Message:
        Permission: bubble.vip
        Message:
          - '&eThis is an example of a'
          - '&emulti-line message!'
      HEX_Example_Message:
        Permission: bubble.vip
        Message:
          - '#ff3393This is an example of a HEX message!'

  # Welcome Messages
  Welcome:

    # Should the message of the day be displayed to users on-join?
    Enable_MOTD: true

    # Should all broadcast messages be forwarded to connected Bungeecord servers?
    # NOTE: This requires the "BubbleBungee" addon (included with the download) to
    # be installed onto your Bungeecord proxy server.
    Bungeecord: false

    # The delay between when the player joins and when the message is
    # sent. Used to separate the MOTD message from other server messages
    # that could backup the chat.
    MOTD_Delay: 1 second

    # The message sent to players on-join.
    Join_MOTD:
      Example_MOTD_1:
        - "&8<chat_line>"
        - "&7Welcome to the server, &b{player}&7!"
        - "&f"
        - "&bWebsite: &fyourserver.com"
        - "&bDiscord: &fdiscord.com/yourserver"
        - "&bTwitter: &ftwitter.com/yourserver"
        - "&8<chat_line>"

    # What sound should be played when the player joins?
    # A list of the compatible values can be found here:
    # https://gist.github.com/NiklasEi/7bd0ffd136f8459df0940e4501d47a8a
    Sound: LEVEL_UP, 1F, 1.5F

  # Join Messages
  Join:

    # Should join messages be broadcast to the server when a player joins?
    Enable_Join_Message: false

    # Should join messages be broadcast to the server when a player quits?
    Enable_Quit_Message: false

    # Should a message be broadcasted to the entire server when a player
    # joins for the first time?
    Enable_First_Join_Broadcast: true

    # If the above option is enabled, the message will only be broadcast to these worlds.
    Worlds:
      - 'world'

# -------------------------------------------------------------------------------------------------
# Chat Section
# -------------------------------------------------------------------------------------------------
Chat:

  # Mentions System
  Mentions:

    # Should players be notified when they are mentioned in the chat (prepended by the @ symbol)?
    Enable: true

    # What color should the player name be highlighted with when mentioned in the chat?
    Color: '&e'

    # What sound should be played when the is mentioned in the chat?
    # A list of the compatible values can be found here:
    # https://gist.github.com/NiklasEi/7bd0ffd136f8459df0940e4501d47a8a
    Sound: ORB_PICKUP

# -------------------------------------------------------------------------------------------------
# The plugin's main prefix. You can manually add this prefix to other messages using the
# {plugin_prefix} placeholder.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&b&l${project.name}&8]&7 "

# -------------------------------------------------------------------------------------------------
# The language used for plugin messages. If the given language is available, the plugin will
# create the appropriate messages_<locale>.yml file in the localization directory.
# -------------------------------------------------------------------------------------------------
Locale: "en"

# -------------------------------------------------------------------------------------------------
# The commands that are used for the plugin. You may edit them here.
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ bubble, bu ]

# -------------------------------------------------------------------------------------------------
# The time (in milliseconds) used to measure plugin operations.
#
# WARNING: DO NOT EDIT THIS!
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# Used to debug plugin features. Only change this if instructed to by the plugin author.
# -------------------------------------------------------------------------------------------------
Debug: [ ]

# -------------------------------------------------------------------------------------------------
# The config file version.
#
# WARNING: DO NOT EDIT THIS!
# -------------------------------------------------------------------------------------------------
Version: 1