#
# Welcome to the main settings file.
#
# For help, visit the official Spigot resource page.
#

Notifications:

  Broadcast:
    Enable: true
    Delay: 90 seconds
    Random_Message: false
    Worlds:
      - 'world'
    Sound: "NOTE_PLING"
    Header: "<smooth_line>"
    Footer: "<smooth_line>"
    Messages:
      Example_Message:
        - "&6This is an example message!"
      Multi_Line_Message:
        - |
          &eThis is an example of a
          multi-line message!

  Welcome:
    Enable_MOTD: true
    MOTD_Delay: 1 second
    Join_MOTD:
      - |
        &8-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
        &7Welcome to the server, &b{player}&7!
        &f
        &bWebsite: &fyourserver.com
        &bDiscord: &fdiscord.com/yourserver
        &bTwitter: &ftwitter.com/yourserver
        &8-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

    Enable_First_Join_Broadcast: true
    Worlds:
      - 'world'
    Join_Broadcasts:
      - "&8[&3&l{server_name}&8]&7 Player &b{player}&7 has joined for the first time!"


Prefix: "&8[&b&lBubble&8]&7 "
Command_Aliases: [ bubble, bu ]
Log_Lag_Over_Milis: 100
Debug: [ ]
Version: 1