# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of Bubble
# !-----------------------------------------------------------------------------------------------!
#
#    For support and documentation, please visit:
#    - https://github.com/markings31/Bubble/wiki
#
# !-----------------------------------------------------------------------------------------------!
#    1) COLOR CODES are supported with the '&' character.
#       - For usage, see http://minecraftwiki.net/wiki/Formatting_codes
#       - When you use them, place quotes around the message like this: "Hello &cworld."
#       - To use HEX colors, use #123456 syntax: "Hello #123456world."
#
#    2) TO HIDE any message, set it to 'none'.
#
#    3) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding. See
#       - https://github.com/markings31/Bubble/wiki/Use-Right-Encoding
#
#    4) JSON is supported.
#       - For usage, see https://github.com/markings31/Bubble/wiki/JSON
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Notifications Section
# -------------------------------------------------------------------------------------------------
Notifications:

  # Broadcast Messages
  Broadcast:

    # Enable broadcast messages?
    Enable: true

    # The delay between each broadcast message.
    Delay: 90 seconds

    # Should the broadcast messages be outputted randomly?
    # Setting this to false will broadcast them in order.
    Random_Message: false

    # Which worlds should the broadcast messages be sent to?
    Worlds:
      - 'world'

    # What sound should be played when a message is broadcast?
    # A list of the compatible values can be found here:
    # https://gist.github.com/NiklasEi/7bd0ffd136f8459df0940e4501d47a8a
    Sound: NOTE_PLING, 1F, 1.5F

  # Welcome Messages
  Welcome:

    # Should the message of the day be displayed to users on-join?
    Enable_MOTD: true

    # The delay between when the player joins and when the message is
    # sent. Used to separate the MOTD message from other server messages
    # that could backup the chat.
    MOTD_Delay: 1 second

    # Should a message be broadcasted to the entire server when a player
    # joins for the first time?
    Enable_First_Join_Broadcast: true

    # What sound should be played when the player joins?
    # A list of the compatible values can be found here:
    # https://gist.github.com/NiklasEi/7bd0ffd136f8459df0940e4501d47a8a
    Sound: LEVEL_UP, 1F, 1.5F

    # If the above option is enabled, the message will only be broadcast to these worlds.
    Worlds:
      - 'world'

# -------------------------------------------------------------------------------------------------
# The plugin's main prefix. You can manually add this prefix to other messages using the
# {plugin_prefix} placeholder.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&b&lBubble&8]&7 "

# -------------------------------------------------------------------------------------------------
# The language used for plugin messages. If the given language is available, the plugin will
# create the appropriate messages_<locale>.yml file in the localization directory.
# -------------------------------------------------------------------------------------------------
Locale: "en"

# -------------------------------------------------------------------------------------------------
# The commands that are used for the plugin. You may edit them here.
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ bubble, bu ]

# -------------------------------------------------------------------------------------------------
# The time (in milliseconds) used to measure plugin operations.
#
# WARNING: DO NOT EDIT THIS!
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# Used to debug plugin features. Only change this if instructed to by the plugin author.
# -------------------------------------------------------------------------------------------------
Debug: [ ]

# -------------------------------------------------------------------------------------------------
# The config file version.
#
# WARNING: DO NOT EDIT THIS!
# -------------------------------------------------------------------------------------------------
Version: 1